environment:
  matrix:
    - CONDA_INSTALL_LOCN: "C:\\Miniconda"
      CONDA_PY: "27"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
      CONDA_PY: "27"

    # - CONDA_INSTALL_LOCN: "C:\\Miniconda35"
    #   CONDA_PY: "35"
    #
    # - CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    #   CONDA_PY: "35"
    #
    # - CONDA_INSTALL_LOCN: "C:\\Miniconda36"
    #   CONDA_PY: "36"
    #
    # - CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    #   CONDA_PY: "36"

install:
  - set CPU_COUNT=2
  - set PYTHONUNBUFFERED=1
  - call "%CONDA_INSTALL_LOCN%\Scripts\activate.bat"
  # update conda
  - conda.exe update --yes --quiet conda
  # add channels
  - conda.exe config --add channels conda-forge
  # config settings
  - conda.exe config --set auto_update_conda false
  # update with conda-forge
  - conda.exe update --yes --quiet conda conda-env conda-build
  - conda.exe info
  # install test dependencies
  - conda.exe install --yes --quiet pytest

build_script:
  - conda.exe build --no-test --quiet recipes/conda
  - conda.exe install --yes --use-local digital_rf

test_script:
  - pytest
