language: python

python: "2.7"

# Note: TWINE_USERNAME and TWINE_PASSWORD are set in Travis settings

matrix:
  fast_finish: true
  include:
    - os: linux
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq cmake libhdf5-dev
        - pip install -r python/dev_requirements.txt
      deploy:
        provider: script
        script: .ci/pypi_upload.sh build/dist/*
        skip_cleanup: true
        on:
          tags: true
    - os: osx
      language: generic
      before_install:
        # because osx image lacks python support, make virtualenv manually
        - virtualenv env -p python2
        - source env/bin/activate
        # have to uninstall oclint to be able to install gcc (required by hdf5)
        - brew cask uninstall oclint
        - brew install hdf5
        - pip install -r python/dev_requirements.txt

install:
  - .ci/build.sh

script:
  - .ci/test.sh
