language: python

sudo: required

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6

before_install:
  - .ci/travis_setup.sh

install:
  - .ci/build.sh

script:
  - .ci/test.sh

# Note: TWINE_USERNAME and TWINE_PASSWORD are set in Travis settings
deploy:
  provider: script
  script: .ci/pypi_upload.sh build/dist/*
  skip_cleanup: true
  on:
    python: 2.7
    condition: $TRAVIS_OS_NAME == 'linux'
    tags: true
