language:
  - c
  - python

compiler: gcc

python: "2.7"

stages:
  - test
  - wheel

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-dev

install:
  - pip install -r dev_requirements.txt

script:
  - _ci/build.sh && _ci/test.sh

jobs:
  include:
    - stage: test
    - stage: wheel
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      before_install: skip
      install: docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/_ci/travis/build_wheels.sh
        - ls wheelhouse/
    - stage: wheel
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
      before_install: skip
      install: docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/_ci/travis/build_wheels.sh
        - ls wheelhouse/
